# Generated by Django 5.2.5 on 2026-03-13 17:55

import django.db.models.deletion
import event_scheduler_v0.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(validators=[event_scheduler_v0.models.validate_date])),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('SOCIAL', 'Social Gathering'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='event_sched_date_ae2637_idx'), models.Index(fields=['user', 'date'], name='event_sched_user_id_f8981c_idx')],
            },
        ),
    ]
